// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqjrmcozjclyxdgdatzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxanJtY296amNseXhkZ2RhdHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NzA2NjMsImV4cCI6MjA2ODA0NjY2M30.RrYi33NemUKHQ7k68N-nDTvlG6kyd6HUbUkSZls0yGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});